language: ruby
rvm:
- 2.2.2
script: bundle exec jekyll build --trace # && bundle exec htmlproof --check-html ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
