# Site settings
title: Tohuw.Net
email: ron@tohuw.net
description: >
  Elucidating Systems Architecture, Operations, & Yak Shaving
baseurl: ""
url: https://tohuw.net
twitter_username: tohuw
github_username:  tohuw

# Custom settings
language: en
author: Ron Scott-Adams
subtitle: Elucidating Systems Architecture, Operations, & Yak Shaving
tipue_search: true
search_url: search
searchbox_text: Search... (type & press enter)
linkedin_username: tohuw
links:
    - name: HighExecutive.Net
      subtitle: (Ruminations of my illustrious wife)
      link: http://highexecutive.net
    - name: UberMarianne.com
      subtitle: (My Sister-In-Law Introspects)
      link: http://ubermarianne.net
    - name: Dadhacker
      subtitle: (Cantankerous and full of good stories)
      link: http://dadhacker.com
    - name: Punching Clouds
      subtitle: (A practical and interesting virtualization blog)
      link: http://punchingclouds.com
    - name: Cormac Hogan
      subtitle: (Virtualization and storage at a comprehenisble depth)
      link: http://cormachogan.com
license_display: true
license_title: "CC BY-NC-SA 4.0"
license_url: https://tohuw.net/rights/
# google_analytics:
# gosquared_sitename:
# piwik_url: https://tohuw.net/stats
# piwik_siteid: 1

# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

# Handling Reading
safe:         false
# include:      [".htaccess"]
exclude:      []
# keep_files:   [".git"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink:     /articles/:title/
paginate_path: /pages/:num/
timezone:      America/New_York

quiet:    false
defaults: []

# Markdown Processors
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
