# Site settings
title: Tohuw.Net
email: ron@tohuw.net
description: >
  Ron Scott-Adams is a Systems Architect and Administrator, with a passion for
  creating, maintaining and explaining well-designed data centers,
  virtualization solutions, and information technology systems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tohuw.net" # the base hostname & protocol for your site
timezone: America/New_York
twitter_username: tohuw
github_username:  tohuw

# Build settings
markdown: kramdown

# Default extension for new posts and pages
post_ext: md
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

# Format titles with titlecase?
titlecase: true
