# Site settings
title: Tohuw.Net
email: ron@tohuw.net
description: >
  Ron Scott-Adams is a Systems Architect and Administrator, with a passion for
  creating, maintaining and explaining well-designed data centers,
  virtualization solutions, and information technology systems.
baseurl: ""
url: "https://tohuw.net"
timezone: America/New_York

# Metadata
language: en
author: Ron Scott-Adams
subtitle: Architecting IT Systems, Operating Blinkenlights, Shaving Yaks

# License
license_display: true
license_title: "CC BY-NC-SA 4.0"
license_url: https://tohuw.net/rights/

# Taxonomy
permalink: /articles/:title
paginate_path: /page/:num/

# Default extension for new posts and pages
post_ext: md
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

# Format titles with titlecase?
titlecase: true

# Build settings
exclude:
  - vendor
  - README.md
markdown: kramdown
minify_html: true
html_press:
  unquoted_attributes: false
  drop_empty_values: false
  strip_crlf: false
  js_minifier_options: false
asset_pipeline:
  stylesheets_dir: 'stylesheets'
  combine_css: true
  compress_css: false
  order_css:
    - normalize.css
    - h5bp.css
    - main.scss
  javascripts_dir: 'javascripts'
  combine_js: true
  compress_js: true
  order_js:
    - jquery-1.11.3.min.js
    - modernizr-2.8.3.min.js
    - lunr.js
    - plugins.js
    - main.js
sass:
  sass_dir: _sass

# google_analytics:
# gosquared_sitename:
# piwik_url: https://tohuw.net/stats
# piwik_siteid: 1

# Search
search_enabled: true
search_placeholder: Search...

# Categories
categories_display: false
category_archive:
  layout: category_archive
  path: topic
  slugify: true

# Tags
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
ignored_tags:

# Social
social_title:
rss_title: icon
twitter_title: icon
twitter_username: tohuw
linkedin_title: icon
linkedin_username: tohuw
github_title: icon
github_username:  tohuw
facebook_title: icon
facebook_username: tohuw
disqus_shortname: tohuw

# Recent Posts List
recentposts_display: true
recentposts_title: More, Here
recentposts_count: 3

# Blogroll
blogroll_title: More, Elsewhere
blogroll:
    - name: HighExecutive.Net
      subtitle: Ruminations of my illustrious wife
      url: http://highexecutive.net
    - name: UberMarianne.com
      subtitle: My Sister-In-Law Introspects
      url: http://ubermarianne.net
    - name: Dadhacker
      subtitle: Cantankerous and full of good stories
      url: http://dadhacker.com
    - name: Punching Clouds
      subtitle: A practical and interesting virtualization blog
      url: http://punchingclouds.com
    - name: Cormac Hogan
      subtitle: Virtualization and storage at a comprehenisble depth
      url: http://cormachogan.com

# Linkblog
linkblog:
  linkpost:
    marker: →
    marker_position: after
  posts:
    marker: false
    marker_position: before

  titlecase: true
  unorphan: true
  permalink_label: Permalink

  # Readtime
  readtime_display: true
  readtime_title: icon
