# Site settings
title: Tohuw.Net
email: ron@tohuw.net
description: >
  Ron Scott-Adams is a Systems Architect and Administrator, with a passion for
  creating, maintaining and explaining well-designed data centers,
  virtualization solutions, and information technology systems.
baseurl: ""
url: "https://tohuw.net"
timezone: America/New_York

# Taxonomy
permalink: /articles/:title/
paginate_path: /pages/:num/

# Default extension for new posts and pages
post_ext: md
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

# Build settings
exclude: [vendor]
markdown: kramdown
# highlighter: rouge
minify_html: false
html_press:
  unquoted_attributes: false
  drop_empty_values: false
  strip_crlf: false
  js_minifier_options: false
asset_pipeline:
  combine_css: true
  compress_css: true
  order_css: []
  combine_js: true
  compress_js: true
  order_js: []

# Social
twitter_username: tohuw
github_username: tohuw

# Linkblog
linkblog:
  linkpost:
    marker: →
    marker_position: after
  posts:
    marker: false
    marker_position: before

  titlecase: true
  unorphan: true
  permalink_label: Permalink
