# Site settings
title: Tohuw.Net
email: ron@tohuw.net
description: > # this means to ignore newlines until "baseurl:"
  Elucidating Systems Architecture, Operations, & Yak Shaving
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tohuw.net" # the base hostname & protocol for your site
twitter_username: tohuw
github_username:  tohuw

# Build settings
markdown: kramdown
