feed_count: 50               # Maximum number of posts in a feed
posts_link_out: true         # Linkposts should direct visitors to the linked site
feed_excerpts: false         # Use post excerpts in feeds
category_feeds: true         # Add a feed for post categories
tag_feeds: false             # Add a feed for post tags
categories: []               # Only add feeds for these categories. (empty adds feeds for all categories)
tags: []                     # Only add feeds for these tags. (empty adds feeds for all tags)

read_more_label:  "Continue reading →"
permalink_label:  "Permalink"

titles:
  main_feed:      Posts - :site_name
  links_feed:     Links - :site_name
  articles_feed:  Posts - :site_name
  category_feed:  Posts about :category - :site_name
  tag_feed:       Posts tagged with :tag - :site_name

permalinks:
  main_feed:      /feeds/
  links_feed:     /feeds/links/
  articles_feed:  /feeds/articles/
  category_feed:  /feeds/topic/:category/
  tag_feed:       /feeds/tag/:tag/
